name: CICD Build
on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --tags --force  # Retrieve annotated tags.
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Setup access token
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Build prep
        run: make clean
      - name: Build
        run: make cicd-build
      - uses: actions/upload-artifact@v3
        with:
          name: bin
          path: bin/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*

      - name: Trigger signing workflow
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/cicd-sign.yml/dispatches \
            -d '{"ref":"${{ github.ref }}"}'
